---
title: "eda_project"
author: "Marckenrold Cadet"
date: "`r Sys.Date()`"
output: 
   html_notebook:
       toc: true 
       toc_float: true
       toc_depth: 2
       theme: united
       highlight: tango
---

```{r}
library(dplyr)
library(readr)
library(tidyverse)
library(ggplot2)
```


```{r}
data <- read_csv("https://raw.githubusercontent.com/Alexburk93/Data_Wrangling_EDA/main/data/suicide_analysis.csv")
                data %>% sample_n(19)
```
Renaming variables and drop unwanted columns
```{r}
# renaming the columns 
data <- data %>%
  rename(`Country_name` = `Country name`,
         `Suicide_Rate` = `Age-standardized suicide rate - Sex: both sexes`,
         `Life_ladder` = `Life Ladder`,
         `Social_support` = `Social support`,
         `Life_expectancy` = `Healthy life expectancy at birth`,
         `Freedom_choices` = `Freedom to make life choices`,
         `Corruption` = `Perceptions of corruption`,
         `Indicator_name` = `Indicator Name`,
         `Indicator_code` = `Indicator Code`)

# drop columns 
# remove the original 'Time' column
data <- select(data, -Variable, -ISIC4...17, -ISIC4...18, -VAR, -MEA, -`Unit Code`)  
data
```
Open space for mark

# AVG GDP over years
## Calculation 
```{r}
avg_gdp_per_year <- data %>% 
  group_by (`Year`) %>% 
  summarise(avg_gpd = mean(`GDP`))

avg_gdp_per_year
```
## Plot 
```{r}
ggplot(avg_gdp_per_year, aes(x = Year, y = avg_gpd)) +
  geom_line(color = "blue") +  
  labs(title = "Average GDP Over Time",
       x = "Year",
       y = "GDP") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = seq(min(avg_gdp_per_year$Year), max(avg_gdp_per_year$Year), by = 1))
```
# AVG Happiness over years
## Calculation 
```{r}
avg_happiness_per_year <- data %>% 
  group_by (`Year`) %>% 
  summarise(avg_happinnes = mean(`Life_ladder`, na.rm = T))

avg_happiness_per_year
```
## Plot 

```{r}
ggplot(avg_happiness_per_year, aes(x = Year, y = avg_happinnes)) +
  geom_point(color = "blue") +  
  labs(title = "Average Happiness Over Time",
       x = "Year",
       y = "Happiness") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = seq(min(avg_happiness_per_year$Year), max(avg_happiness_per_year$Year), by = 1))
```

# AVG Suicide Rates over years
## Calculation 
```{r}
avg_Suicide_Rate_per_year <- data %>% 
  group_by (`Year`) %>% 
  summarise(avg_Suicide_Rate = mean(`Suicide_Rate`, na.rm = T))

avg_Suicide_Rate_per_year
```
## Plot 

```{r}
ggplot(avg_Suicide_Rate_per_year, aes(x = Year, y = avg_Suicide_Rate)) +
  geom_point(color = "blue") +  
  labs(title = "Average Happiness Over Time",
       x = "Year",
       y = "Happiness") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_continuous(breaks = seq(min(avg_Suicide_Rate_per_year$Year), max(avg_Suicide_Rate_per_year$Year), by = 1))



```




```{r}
avg_gdp_per_country <- data %>% 
  group_by (`Country_name`) %>% 
  summarise(avg_gpd = mean(`GDP`))

avg_gdp_per_country
```

